<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AQCPM</RootNamespace>
    <AssemblyName>AQC.PM</AssemblyName>
    <Product>AQC Project Management</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aorms.Bridge\Aorms.Bridge.csproj" />
  </ItemGroup>
</Project>